export const ORDERS = [
  {
    orderNumber: '10001',
    name: 'Frozen Yogurt',
    numberOfItems: 2,
    totalAmount: 500,
    status: 'Order Received',
  },
  {
    orderNumber: '10002',
    name: 'Ice cream sandwich',
    numberOfItems: 3,
    totalAmount: 540,
    status: 'Order Received',
  },
  {
    orderNumber: '10003',
    name: 'Eclair',
    numberOfItems: 2,
    totalAmount: 100,
    status: 'Order Received',
  },
  {
    orderNumber: '10004',
    name: 'Cupcake',
    numberOfItems: 20,
    totalAmount: 5000,
    status: 'Ready to serve',
  },
  {
    orderNumber: '10005',
    name: 'Gingerbread',
    numberOfItems: 12,
    totalAmount: 500,
    status: 'Ready to serve',
  },
  {
    orderNumber: '10006',
    name: 'Jelly bean',
    numberOfItems: 2,
    totalAmount: 500,
    status: 'Order Received',
  },
  {
    orderNumber: '10007',
    name: 'Lollipop',
    numberOfItems: 2,
    totalAmount: 500,
    status: 'Ready to serve',
  },
  {
    orderNumber: '10008',
    name: 'Honeycomb',
    numberOfItems: 2,
    totalAmount: 500,
    status: 'Preparing',
  },
  {
    orderNumber: '10009',
    name: 'Donut',
    numberOfItems: 52,
    totalAmount: 570,
    status: 'Order Received',
  },
  {
    orderNumber: '100010',
    name: 'KitKat',
    numberOfItems: 5,
    totalAmount: 450,
    status: 'Preparing',
  },
];
